[versions]
agp = "8.13.2"
kotlin = "2.2.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.13.2" }

# Tuya
tuya = { group = "com.thingclips.smart", name = "thingsmart", version = "6.11.1" }
tuyaLock = { group = "com.thingclips.smart", name = "thingsmart-lock-sdk", version = "6.10.0" }
soLoader = { group = "com.facebook.soloader", name = "soloader", version = "0.12.1" }
fastJson = { group = "com.alibaba", name = "fastjson", version = "2.0.60" }
urlConnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version = "5.3.2" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

[bundles]
tuya = ["tuya", "tuyaLock", "soLoader", "fastJson", "urlConnection"]
